name: patitas
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.0.3
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.3
  sqlite3_flutter_libs: ^0.5.23
  sqflite_common_ffi: ^2.3.3
  desktop_window: ^0.4.0
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  dartz: ^0.10.1
  go_router: ^14.3.0
  firebase_core: ^3.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  bloc_test: ^9.0.2
  build_runner: ^2.1.2
  mockito: ^5.0.15
  mocktail: ^0.2.0

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/database/patitas.db
    - assets/imagenes/logov4.png
  #   - assets/menu_opts.json
  #   - images/a_dot_ham.jpeg
