// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlziNzpgCaa-XioXBOzqCGTVuJcOravaw',
    appId: '1:210073379809:web:2d27b640d445a5f314a8a0',
    messagingSenderId: '210073379809',
    projectId: 'patitas-1e81e',
    authDomain: 'patitas-1e81e.firebaseapp.com',
    storageBucket: 'patitas-1e81e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2UtnuIXgYKvzvcrZ_gHlnlRTKU4eatvg',
    appId: '1:210073379809:android:a1b51b4df0b9744214a8a0',
    messagingSenderId: '210073379809',
    projectId: 'patitas-1e81e',
    storageBucket: 'patitas-1e81e.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlziNzpgCaa-XioXBOzqCGTVuJcOravaw',
    appId: '1:210073379809:web:59e7e79d673d589c14a8a0',
    messagingSenderId: '210073379809',
    projectId: 'patitas-1e81e',
    authDomain: 'patitas-1e81e.firebaseapp.com',
    storageBucket: 'patitas-1e81e.appspot.com',
  );
}
