@startuml

package reposotory <<folder>> {
  abstract CasoRepository {
    Future<List<Caso>> todosLosCasos()
    Future<List<Caso>> todosLosCasosPendientes()
    Future<Caso> getCasoById(int casoId)
    void agregarCaso(Caso nuevoCaso)
    void bajarCaso(int casoId)
  }
  abstract UsuarioRepository {
    Future<List<Usuario>> todosLosUsuarios()
    Future<List<Usuario>> todosLosUsuariosActivos()
    Future<Usuario> getUsuarioById(int usuarioId)
    void agregarUsuario(Usuario nuevoUsuario)
    void bajarUsuario(int usuarioId)
  }
}

package reposotory_impl <<folder>> {
  class CasoRepositoryImpl {
    Future<List<Caso>> todosLosCasos()
    Future<List<Caso>> todosLosCasosPendientes()
    Future<Caso> getCasoById()
    void agregarCaso()
    void bajarCaso()
  }
  class UsuarioRepositoryImpl {
    Future<List<Usuario>> todosLosUsuarios()
    Future<List<Usuario>> todosLosUsuariosActivos()
    Future<Usuario> getUsuarioById(int usuarioId)
    void agregarUsuario(Usuario nuevoUsuario)
    void bajarUsuario(int usuarioId)
  }
}

package use_cases <<folder>> {
  class AdminPatitasUC {
    UsuarioRepository usrRepo 
    CasoRepository casoRepo
    String registrarse(String nombre, String apellido, String telefonoOEmail)
    void iniciarSesion(context)
    void adoptar()
    void darTransito()
    void registrarNuevoCaso()
    Future<List<Caso>> getCasosAdopcion()
    Future<List<Caso>> getCasosTransito()
  }
}

package entity <<folder>>{
  class Usuario {
      -Integer idUsuario
      -String email
      -String contrasenia
      -String dni
      -String direccion
      -String distrito
      -String telefono
      -String nombre
      -String apellido
      -String foto
      -date fechaNacimiento
      -date fechaRegistro
      -date fechaBaja
  }

  class Caso {
      -Integer idCaso
      -String direccion
      -String distrito
      -String contacto
      -String foto
      -date fechaRegistro
      -date fechaBaja
      -date fechaResolucion
  }
}

package enum <<folder>> {
  enum EstadoCaso {
      PENDIENTE
      ADOPTADO
      EN_TRANSITO
  }

  enum TipoDeCaso {
      ADOPCION
      TRANSITO 
      BUSQUEDA
  }

  enum TiposDeUsuario {
      NORMAL
      ADMINISTRADOR
  }
}
Usuario "1" o-left- "0..*" Caso : registrante
Usuario "1" o-- "0..*" Caso : adoptante
Caso "0..*" -- "1" TipoDeCaso : tipoCaso
Caso "0..*" -- "1" EstadoCaso : estado
Usuario "0..*" -- "1" TiposDeUsuario : tipoUsuario
CasoRepositoryImpl -down-|> CasoRepository 
UsuarioRepositoryImpl --|> UsuarioRepository
CasoRepository ..> Caso
UsuarioRepository ..> Usuario
AdminPatitasUC -down-> CasoRepository
AdminPatitasUC -down-> UsuarioRepository

@enduml
