@startuml
:Usuario: as u
:Visitante: as v
:Admin: as a 
a --> (registrar nuevo caso)
a --> (marcar caso como resuelto)
a --> (administrar usuarios)
a --> u
u --> (ver casos)
(ver casos) <|.. (compartir)
(ver casos) <|.. (adoptar)
(ver casos) <|.. (dar transito)
v --> (iniciar sesión)
v --> (registrarse)


@enduml

